### PR TITLE
Readme Edit1

### PR DESCRIPTION
**Pull request by kbokhari**
changed variable names and spelling.

### CODE REVIEW

**Comment by warahfel** [comment]
Looks good

**Comment by warahfel** [comment]
Hey I just had an odd idea. What if we checked to see if there is any correlation between doctor availability and HIV/AIDS?
I'm thinking that maybe... if there are more doctors in an area there might be better general medical knowledge and advice passed around throughout the population which might have an effect on the sexual behavior of a that population.. maybe?

**Comment by kbokhari** [comment]
That is a possibility. We may also see increased access to contraceptives and medication. Of course we might also be worried about increased diagnosis so the numbers may initially be inflated. We can graph the data over time in a few countries and see what happens!

**Comment by warahfel** [comment]
That's true, I hadn't thought of that. Sounds good!

**Pull request merged**
